test_dataset:
  dataset:
    name: image-folder-cv2-8bit
    args:
      root_path: ### Your data path i have provided the train images in data folders use test folder and then kodak
  wrapper:
    name: ABCD_test-8bit
    args:
      inpdepth: 4
      gtdepth: 8
  batch_size: 1
